# -*- coding: utf-8 -*-
"""DeepConvNet_alldata_allchannel_rangefour_CAR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dNEj6n5BaawTAM-Ck2zsHequbuqW0xQx
"""

from google.colab import drive
drive.mount('/gdrive')

import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

import scipy.io
from sklearn.preprocessing import Normalizer
import pandas
import numpy as np
from sklearn.utils import shuffle
import random
import matplotlib.pyplot as plt
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Activation, Permute, Dropout
from tensorflow.keras.layers import Conv2D, MaxPooling2D, AveragePooling2D
from tensorflow.keras.layers import SeparableConv2D, DepthwiseConv2D
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import SpatialDropout2D
from tensorflow.keras.regularizers import l1_l2
from tensorflow.keras.layers import Input, Flatten
from tensorflow.keras.constraints import max_norm
from tensorflow.keras import backend as K

from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, BatchNormalization, Activation
from keras.layers.convolutional import Conv2D, MaxPooling2D
from keras.constraints import maxnorm
from keras.utils import np_utils
import pickle
import numpy as np
from numpy.random import seed
import tensorflow as tf
from tensorflow.keras.models import Model
import matplotlib.pyplot as plt
from tensorflow.keras.layers.experimental import preprocessing
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.applications import EfficientNetB0
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve
from sklearn.metrics import auc
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
import matplotlib
import matplotlib.pyplot as plt
from matplotlib import image
from matplotlib import pyplot
import numpy as np
import random
from PIL import Image
from numpy import asarray
from sklearn.utils import class_weight
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold
import sklearn.metrics as metrics
from keras.utils.np_utils import to_categorical
from tensorflow.keras import initializers
from tensorflow.keras import regularizers
from keras.preprocessing.image import ImageDataGenerator
from keras import backend as K

from sklearn.datasets import make_circles
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import os
from tensorflow.keras.layers import *
from tensorflow.keras.models import Model
from tensorflow.keras import backend as K
from tensorflow.keras.utils import get_custom_objects

matl = scipy.io.loadmat('/content/drive/MyDrive/Lie_Detection_Project/Data/L_alldata_allchannel_rangefour_CAR_cnn.mat')
print(matl)
l = matl['alldata_allchannel_probe_rangefour_L']
#print('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%')
#print(l)
#print(l.shape)
#print(l[2])
#scaler = Normalizer().fit(t)
#normalizedX = scaler.transform(t)
#print(normalizedX[0])

matt = scipy.io.loadmat('/content/drive/MyDrive/Lie_Detection_Project/Data/T_alldata_allchannel_rangefour_CAR_cnn.mat')
print(matt)
t = matt['alldata_allchannel_probe_rangefour_T']
#print('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%')
#print(t)
#print(t.shape)
#print(t[0])

data = np.concatenate((l, t), axis=0)
print(data.shape)
#print(data)

###### signal(data)
signal_L = []
for i in range(750):
  signal_l = l[19*i: 19*(i+1)]
  signal_L.append(signal_l)

print(len(signal_L))
#print(signal_L[0])
#w = signal_L[0]
#print(w.shape)    
#a = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
#print(a[0,1])

signal_T = []
for i in range(690):
  signal_t = t[19*i: 19*(i+1)]
  signal_T.append(signal_t)

print(len(signal_T))

Signal = np.concatenate((signal_L, signal_T), axis=0)
print(Signal.shape)

#sig_test = signal[0]
#print(sig_test.shape)
#print(sig_test)

####### Label
L = np.zeros(750)
T = np.ones(690)

Label = np.concatenate((L, T), axis=0)
print(Label.shape)
#print(label)

####### Shuffle signal and label together
#signal, label = shuffle(signal, label, random_state=0)

#print(label)
#print(signal.shape)

#plt.plot(signal[0,10])
#plt.show()
#################################################33
#print(signal[0])
randomize = np.arange(len(Label))
#print(randomize)
random.seed(7)
random.shuffle(randomize)
print(randomize)
#print(randomize[0])
data = Signal[randomize]
#r = signal[randomize[0]]
#print(r)
label = Label[randomize]
#print(label)
#print('#######################')
#print(data)
#print('#######################')

#print(Signal[705])

#arr = signal
#x = np.where(arr == signal[0])
#print(x)

#signal = shuffle(signal, random_state=0)
#label = shuffle(label, random_state=0)
#print(label)

#print(signal)
#print(signal.shape)

##### Define Model DeepConvNet #####

def DeepConvNet(nb_classes, Chans = 64, Samples = 256,
                dropoutRate = 0.5):
    """ Keras implementation of the Deep Convolutional Network as described in
    Schirrmeister et. al. (2017), Human Brain Mapping.
    
    This implementation assumes the input is a 2-second EEG signal sampled at 
    128Hz, as opposed to signals sampled at 250Hz as described in the original
    paper. We also perform temporal convolutions of length (1, 5) as opposed
    to (1, 10) due to this sampling rate difference. 
    
    Note that we use the max_norm constraint on all convolutional layers, as 
    well as the classification layer. We also change the defaults for the
    BatchNormalization layer. We used this based on a personal communication 
    with the original authors.
    
                      ours        original paper
    pool_size        1, 2        1, 3
    strides          1, 2        1, 3
    conv filters     1, 5        1, 10
    
    Note that this implementation has not been verified by the original 
    authors. 
    
    """

    # start the model
    input_main   = Input((1, Chans, Samples))
    block1       = Conv2D(25, (1, 5), 
                                 input_shape=(1, Chans, Samples),
                                 kernel_constraint = max_norm(2., axis=(0,1,2)), padding='same')(input_main)
    block1       = Conv2D(25, (Chans, 1),
                                 kernel_constraint = max_norm(2., axis=(0,1,2)), padding='same')(block1)
    block1       = BatchNormalization(axis=1, epsilon=1e-05, momentum=0.1)(block1)
    block1       = Activation('elu')(block1)
    block1       = MaxPooling2D(pool_size=(1, 2), strides=(1, 2), padding='same')(block1)
    block1       = Dropout(dropoutRate)(block1)
  
    block2       = Conv2D(50, (1, 5),
                                 kernel_constraint = max_norm(2., axis=(0,1,2)), padding='same')(block1)
    block2       = BatchNormalization(axis=1, epsilon=1e-05, momentum=0.1)(block2)
    block2       = Activation('elu')(block2)
    block2       = MaxPooling2D(pool_size=(1, 2), strides=(1, 2), padding='same')(block2)
    block2       = Dropout(dropoutRate)(block2)
    
    block3       = Conv2D(100, (1, 5),
                                 kernel_constraint = max_norm(2., axis=(0,1,2)), padding='same')(block2)
    block3       = BatchNormalization(axis=1, epsilon=1e-05, momentum=0.1)(block3)
    block3       = Activation('elu')(block3)
    block3       = MaxPooling2D(pool_size=(1, 2), strides=(1, 2), padding='same')(block3)
    block3       = Dropout(dropoutRate)(block3)
    
    block4       = Conv2D(200, (1, 5),
                                 kernel_constraint = max_norm(2., axis=(0,1,2)), padding='same')(block3)
    block4       = BatchNormalization(axis=1, epsilon=1e-05, momentum=0.1)(block4)
    block4       = Activation('elu')(block4)
    block4       = MaxPooling2D(pool_size=(1, 2), strides=(1, 2), padding='same')(block4)
    block4       = Dropout(dropoutRate)(block4)
    
    flatten      = Flatten()(block4)
    
    dense        = Dense(nb_classes, kernel_constraint = max_norm(0.5))(flatten)
    softmax      = Activation('sigmoid')(dense)
    
    return Model(inputs=input_main, outputs=softmax)

##### For generilizing Model #####
seed(1)
tf.random.set_seed(2)

initializer = tf.keras.initializers.GlorotUniform(seed=7)

label_n = np.array(label)
data_n = data.astype('float32')

#data_cnn = data_n.transpose((0,2,1))

data_cnn = np.expand_dims(data_n, axis=1)
print(data_cnn.shape)

j = 1

##### Define and train model #####

kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=7)

for train, test in kfold.split(data_cnn, label_n):

    print('\nFold ', j)

    ## For generilizing Model
    seed(1)
    tf.random.set_seed(2)

    ## Initializer and Batch and Epochs
    initializer = tf.keras.initializers.GlorotUniform(seed=7)

    X_train = data_cnn[train]
    y_train = label_n[train]
    X_test = data_cnn[test]
    y_test = label_n[test]
    unique_train, counts_train = np.unique(y_train, return_counts=True)
    print("lables of train in fold", counts_train)
    X_test, X_valid, y_test, y_valid = train_test_split(X_test, y_test, test_size=0.5, random_state=42, stratify=y_test)
    uniquet_test, counts_test = np.unique(y_test, return_counts=True)
    print("lables of test in fold", counts_test)
    unique_valid, counts_valid = np.unique(y_valid, return_counts=True)
    print("lables of valid in fold", counts_valid)
    print(y_valid)
    print(y_test)
    print("train lables: ", y_train)

    ## Class weight for imbalance classification
    #class_weights = {0: 0.93, 1: 1.07}
    #print(class_weights)
    #class_weight=class_weights,
    

    model = DeepConvNet(1, Chans = 19, Samples = 250, dropoutRate = 0.5)
    #model.compile(optimizer = 'adam', loss = 'categorical_crossentropy')
    opt = keras.optimizers.Adam(learning_rate=0.0001)

    # Compiling and fitting
    #model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])
    model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])
    model.summary()

    hist = model.fit(X_train, y_train, batch_size=24, validation_data=(X_valid, y_valid),
                               epochs=800, 
                     callbacks=[EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=400, min_delta=0.1, restore_best_weights=True),
                               ModelCheckpoint('/content/drive/MyDrive/Lie_Detection_Project/Code/DeepConvNet_alldata_allchannel_rangefour_CAR/Best_Model/bestmodel'+str(j)+'.h5', monitor='val_accuracy', mode='max', verbose=1,
                                               save_best_only=True)]
                     )
    

    j += 1