# -*- coding: utf-8 -*-
"""Xception_RP_alldata_allchannel_rangefour_concat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L9UZwqGMqoWyb48fUZzzf8DcZe1p-yZQ
"""

from google.colab import drive
drive.mount('/gdrive')

import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

import pickle
with open('/gdrive/My Drive/Lie_Detection_Project/Data/x_RP_alldata_allchannel_rangefour_concat.pickle', 'rb') as f:
    X = pickle.load(f)
with open('/gdrive/My Drive/Lie_Detection_Project/Data/y_RP_alldata_allchannel_rangefour_concat.pickle', 'rb') as g:
    y = pickle.load(g)
    print(X.shape)

import numpy
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, BatchNormalization, Activation
from keras.layers.convolutional import Conv2D, MaxPooling2D
from keras.constraints import maxnorm
from keras.utils import np_utils
import pickle
import numpy as np
from numpy.random import seed
import tensorflow as tf
from tensorflow.keras.models import Model
import matplotlib.pyplot as plt
from tensorflow.keras.layers.experimental import preprocessing
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.applications import EfficientNetB0
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve
from sklearn.metrics import auc
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
import matplotlib
import matplotlib.pyplot as plt
from matplotlib import image
from matplotlib import pyplot
import numpy as np
import random
from PIL import Image
from numpy import asarray
from sklearn.utils import class_weight
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold
import sklearn.metrics as metrics
from keras.utils.np_utils import to_categorical
from tensorflow.keras import initializers
from tensorflow.keras import regularizers
from keras.preprocessing.image import ImageDataGenerator

from sklearn.datasets import make_circles
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix

## For generilizing Model
seed(1)
tf.random.set_seed(2)

IMG_SIZE = 299
NUM_CLASSES = 2

X = X.astype('float32')
print(X.shape)
X = X/255.0

y = np.array(y) #It seems to be necessary because if you do not implement array, you will get error
print(y.dtype)

## Initializer and Batch and Epochs
initializer = tf.keras.initializers.GlorotUniform(seed=7)
batch_size = 24
epochs = 300  # @param {type: "slider", min:10, max:100}
#hist = model.fit(X_BCC_SCC, epochs=epochs, validation_split=0.1,)

j = 1
train_acc_10fold = []
test_acc_10fold = []
accuracy_10fold = []
precision_10fold = []
recall_10fold = []
specificity_10fold = []
f1_10fold = []
auc_10fold = []
matrix_10fold = []
hist_accuracy = []
hist_val_accuracy = []
hist_loss = []
hist_val_loss = []
fpr_keras_10fold = []
tpr_keras_10fold = []
thresholds_keras_10fold = []

kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=7)

for train, test in kfold.split(X, y):

    print('\nFold ', j)

    ## For generilizing Model
    seed(1)
    tf.random.set_seed(2)

    ## Initializer and Batch and Epochs
    initializer = tf.keras.initializers.GlorotUniform(seed=7)

    X_train = X[train]
    y_train = y[train]
    X_test = X[test]
    y_test = y[test]
    unique_train, counts_train = np.unique(y_train, return_counts=True)
    print("lables of train in fold", counts_train)
    X_test, X_valid, y_test, y_valid = train_test_split(X_test, y_test, test_size=0.5, random_state=42, stratify=y_test)
    uniquet_test, counts_test = np.unique(y_test, return_counts=True)
    print("lables of test in fold", counts_test)
    unique_valid, counts_valid = np.unique(y_valid, return_counts=True)
    print("lables of valid in fold", counts_valid)
    print(y_valid)
    print(y_test)
    print("train lables: ", y_train)

    ## Class weight for imbalance classification
    #class_weights = {0: 2.5, 1: 0.625}
    #class_weights = class_weight.compute_class_weight('balanced', np.unique(y_train), y_train)
    #class_weights = {i:class_weights[i] for i in range(2)}
    #class_weights = {0: 0.53, 1: 7.79}
    #print(class_weights)

    # New_Model
    base_model = tf.keras.applications.Xception(
        weights='imagenet',
        input_shape=(IMG_SIZE, IMG_SIZE, 3),
        include_top=False,
        pooling='max')

    x = base_model.output
    tf.keras.regularizers.l2(l2=0.0001)
    x = Dense(units=64, kernel_regularizer='l2', kernel_initializer=initializer, activation='relu')(x)
    tf.keras.regularizers.l2(l2=0.0001)
    x = Dense(units=1, kernel_regularizer='l2', kernel_initializer=initializer, activation='sigmoid')(x)

    model = Model(base_model.input, x)

    # CallBack
    #callback = [EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=5, min_delta=0.0001),
    #           ModelCheckpoint('bestmodel.h5', monitor='val_accuracy', mode='max', verbose=1, save_best_only=True)]
    # optimizer
    opt = keras.optimizers.Adam(learning_rate=0.0001)

    # Compiling and fitting
    #model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])
    model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])

    # This section is for colab error, when it breaks and started from first fold
    if j == 1:
       print('best model of fold '+str(j)+' was saved')
       j += 1
       continue

    hist = model.fit(X_train, y_train, batch_size=batch_size, validation_data=(X_valid, y_valid),
                               epochs=epochs,
                     callbacks=[EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=110, min_delta=0.1, restore_best_weights=True),
                               ModelCheckpoint('/gdrive/My Drive/Lie_Detection_Project/Code/Xception_RP_alldata_allchannel_rangefour_concat/Best_Model/bestmodel'+str(j)+'.h5', monitor='val_accuracy', mode='max', verbose=1,
                                               save_best_only=True)]
                     )
    j += 1